// 存储键名常量
export const STORAGE_KEYS = {
  BOOKS: 'books',
  SETTINGS: 'settings',
  BOOKMARKS: 'bookmarks',
  CURRENT_BOOK_ID: 'currentBookId'
};

// 默认设置
export const DEFAULT_SETTINGS = {
  theme: 'eye-care',
  fontSize: 18,
  fontFamily: 'Source Han Serif SC',
  lineHeight: 1.8,
  pageFlip: 'none',
  autoScroll: false,
  autoScrollSpeed: 30
};

// 主题配置
export const THEMES = {
  light: {
    name: '白天',
    background: '#FFFFFF',
    text: '#333333',
    buttonBg: '#F8F9FA',
    accent: '#007BFF'
  },
  sepia: {
    name: '护眼',
    background: '#F4ECD8',
    text: '#5B4636',
    buttonBg: '#EDE4D3',
    accent: '#8B4513'
  },
  dark: {
    name: '夜间',
    background: '#1A1A1A',
    text: '#E0E0E0',
    buttonBg: '#2D2D2D',
    accent: '#6DB3F2'
  },
  'eye-care': {
    name: '深色',
    background: '#C8E6C9',
    text: '#2E4A2E',
    buttonBg: '#A5D6A7',
    accent: '#4CAF50'
  }
};

// 章节正则 - 来自原 Flask 应用
export const CHAPTER_REGEX = /\n第[一二三四五六七八九十百千万1234567890]+[章节].*\n/;

// 字体选项
export const FONT_FAMILIES = [
  'Source Han Serif SC',
  '宋体',
  '黑体',
  '微软雅黑',
  '楷体',
  'serif',
  'sans-serif'
];

// 翻页方式
export const PAGE_FLIP_OPTIONS = [
  { value: 'none', label: '无' },
  { value: 'click', label: '点击' },
  { value: 'scroll', label: '滚动' }
];

// 皮肤定义 - 来自 userscript 8.0.5
export const SKINS = {
  "缺省皮肤": "",
  "暗色皮肤": "body { color: #666; background-color: rgba(0,0,0,.1); } .title { color: #222; }",
  "白底黑字": "body { color: black; background-color: white;} .title { font-weight: bold; border-bottom: 0.1em solid; margin-bottom: 1.857em; padding-bottom: 0.857em;}",
  "夜间模式": "body { color: #939392; background: #2d2d2d; } .reader-actions { filter: invert(90%); } .chapter-content img { background-color: #c0c0c0; } .chapter-title { color: #939392; }",
  "夜间模式1": "body { color: #679; background-color: black; } .reader-actions { filter: invert(90%); } .chapter-title { color: #3399FF; background-color: #121212; }",
  "夜间模式2": "body { color: #AAAAAA; background-color: #121212; } .reader-actions { filter: invert(90%); } .chapter-content img { background-color: #c0c0c0; } .chapter-title { color: #3399FF; background-color: #121212; } a { color: #E0BC2D; } a:link { color: #E0BC2D; } a:visited { color:#AAAAAA; } a:hover { color: #3399FF; } a:active { color: #423F3F; }",
  "夜间模式（多看）": "body { color: #4A4A4A; background: #101819; } .reader-actions { filter: invert(90%); } .chapter-content img { background-color: #c0c0c0; }",
  "橙色背景": "body { color: #24272c; background-color: #FEF0E1; }",
  "绿色背景": "body { color: black; background-color: #d8e2c8; }",
  "绿色背景2": "body { color: black; background-color: #CCE8CF; }",
  "蓝色背景": "body { color: black; background-color: #E7F4FE; }",
  "棕黄背景": "body { color: black; background-color: #C2A886; }",
  "经典皮肤": "body { color: black; background-color: #EAEAEE; } .chapter-title { background-color: #f0f0f0; }",
  "绿色亮字": "body, .toc-sidebar, .reader-header { color: rgb(187,215,188); background-color: rgb(18,44,20); } .reader-actions { filter: invert(90%); }",
  "图书双层": "body { color: #black; background: #ECE8D7; } .reader-main { background: #E8E6DA; padding-left: 4rem; padding-right: 4rem; border: 1px solid rgba(211,211,211,0.25); }"
};

// 简繁转换映射表 (简化版)
export const ZH_TW_MAP = {
  '干': '乾',
  '干': '幹',
  '后': '後',
  '发': '發',
  '发': '頭髮',
  '里': '裡',
  '余': '餘',
  '只': '隻',
  '发': '髮',
  '复': '複',
  '复': '復',
  '历': '歷',
  '历': '曆',
  '丑': '醜',
  '并': '並',
  '术': '術',
  '术': '術',
  '朴': '樸',
  '冲': '衝',
  '准': '準',
  '减': '減',
  '几': '幾',
  '凡': '幾',
  '窗': '窓',
  '系': '系統',
  '舞': '舞',
  '别': '別',
  '别': '彆',
  '拼': '拚',
  '旋': '鏇',
  '曾': '曾',
  '曾': '層',
  '会': '會',
  '合': '合',
  '周': '週',
  '回': '回',
  '坛': '壇',
  '宁': '寧',
  '令': '令',
  '台': '臺',
  '表': '錶',
  '丑': '醜',
  '尸': '屍',
  '局': '局限',
  '层': '層',
  '布': '佈',
  '吊': '弔',
  '吃': '吃',
  '后': '后',
  '向': '嚮',
  '回': '回',
  '团': '團',
  '执': '執',
  '场': '場',
  '坏': '壞',
  '壞': '壞',
  '复': '復',
  '够': '夠',
  '奖': '獎',
  '妆': '妝',
  '并': '並',
  '开': '開',
  '异': '異',
  '弃': '棄',
  '弑': '弒',
  '形': '形',
  '彩': '採',
  '待': '待',
  '复': '復',
  '急': '急',
  '惩': '懲',
  '怀': '懷',
  '恆': '恒',
  '恋': '戀',
  '战': '戰',
  '批': '批',
  '折': '摺',
  '护': '護',
  '报': '報',
  '搭': '搭',
  '朴': '樸',
  '杂': '雜',
  '权': '權',
  '条': '條',
  '来': '來',
  '杰': '傑',
  '板': '闆',
  '构': '構',
  '枱': '櫃',
  '枯': '枯',
  '栈': '棧',
  '梦': '夢',
  '梯': '梯',
  '械': '機械',
  '棉': '棉',
  '极': '極',
  '笼': '籠',
  '筑': '築',
  '篋': '篋',
  '粤': '粵',
  '糖': '糖',
  '糞': '糞',
  '系': '系統',
  '索': '索',
  '紫': '紫',
  '累': '累',
  '细': '細',
  '纤': '纖',
  '织': '織',
  '网': '網',
  '置': '置',
  '罚': '罰',
  '羡': '羡',
  '群': '群',
  '翘': '翹',
  '听': '聽',
  '肥': '肥',
  '自动': '自動',
  '临': '臨',
  '脱': '脫',
  '临': '監',
  '肿': '腫',
  '肠': '腸',
  '脸': '臉',
  '脏': '髒',
  '脏': '內臟',
  '临': '蒞',
  '台': '台',
  '舘': '館',
  '舒': '舒',
  '范': '範',
  '茂': '茂',
  '茶': '茶',
  '莱': '萊',
  '著': '著',
  '蚂': '螞',
  '虽': '雖然',
  '蚀': '蝕',
  '蚊': '蚊',
  '蚌': '蚌',
  '衤': '衣',
  '裁': '裁',
  '装': '裝',
  '里': '里',
  '复': '覆',
  '补': '補',
  '表': '錶',
  '见': '見',
  '觉': '覺',
  '观': '觀',
  '觏': '覯',
  '觎': '覦',
  '角': '角',
  '订': '訂',
  '讦': '訐',
  '计': '計',
  '讥': '譏',
  '讵': '詎',
  '讶': '訝',
  '讷': '訥',
  '赴': '赴',
  '赵': '趙',
  '赶': '趕',
  '践': '踐',
  '踪': '蹤',
  '踱': '踱',
  '蹩': '蹩',
  '跃': '躍',
  '车': '車',
  '轨': '軌',
  '轩': '軒',
  '软': '軟',
  '轰': '轟',
  '轿': '轎',
  '较': '較',
  '辔': '轡',
  '辛': '辣',
  '辞': '辭',
  '辫': '辮',
  '农': '農',
  '迂': '迂',
  '迓': '訝',
  '迥': '迥',
  '迭': '疊',
  '迩': '邇',
  '迥': '迥',
  '邮': '郵',
  '邦': '邦',
  '邨': '村',
  '那': '那',
  '鄴': '鄴',
  '酒': '酒',
  '酓': '酓',
  '部分': '部分',
  '里': '里',
  '鉴': '鑒',
  '针': '針',
  '钓': '釣',
  '钮': '鈕',
  '钳': '鉗',
  '钟': '鐘',
  '锤': '錘',
  '钻': '鑽',
  '钱': '錢',
  '锋': '鋒',
  '错': '錯',
  '锡': '錫',
  '镏': '鎦',
  '镇': '鎮',
  '镜': '鏡',
  '长': '長',
  '门': '門',
  '闭': '閉',
  '闲': '閑',
  '间': '間',
  '阀': '閥',
  '阁': '閣',
  '阀': '閥',
  '关': '關',
  '陈': '陳',
  '陆': '陸',
  '阳': '陽',
  '阴': '陰',
  '阵': '陣',
  '阶': '階',
  '阳': '陽',
  '陆': '陸',
  '陕': '陝',
  '陞': '升',
  '隔': '隔',
  '隐': '隱',
  '难': '難',
  '雪': '雪',
  '云': '雲',
  '电': '電',
  '需': '需',
  '霉': '霉',
  '霖': '霖',
  '静': '靜',
  '面': '面',
  '革': '革',
  '靳': '靳',
  '靴': '靴',
  '鞑': '韃',
  '韦': '韋',
  '韧': '韌',
  '韩': '韓',
  '韪': '韙',
  '音': '音',
  '韶': '韶',
  '韵': '韻',
  '响': '響',
  '页': '頁',
  '顶': '頂',
  '顷': '頃',
  '项': '項',
  '顺': '順',
  '须': '須',
  '顾': '顧',
  '顿': '頓',
  '预': '預',
  '顽': '頑',
  '顾': '顧',
  '领': '領',
  '颇': '頗',
  '颈': '頸',
  '颐': '頤',
  '频': '頻',
  '颓': '頹',
  '颗': '顆',
  '题': '題',
  '额': '額',
  '风': '風',
  '飘': '飄',
  '飞': '飛',
  '飨': '饗',
  '饱': '飽',
  '馀': '餘',
  '馅': '餡',
  '馆': '館',
  '饲': '飼',
  '首': '首',
  '香': '香',
  '马': '馬',
  '驮': '馱',
  '驯': '馴',
  '驰': '馳',
  '驱': '驅',
  '驳': '駁',
  '驴': '驢',
  '驶': '駛',
  '驵': '駔',
  '骄': '驕',
  '骆': '駱',
  '骇': '駭',
  '骡': '騾',
  '骠': '驃',
  '鲍': '鮑',
  '鲜': '鮮',
  '鳄': '鱷',
  '鲗': '鰂',
  '鳝': '鱔',
  '鳞': '鱗',
  '鱼': '魚',
  '鲜': '鮮',
  '鸣': '鳴',
  '鸿': '鴻',
  '鹅': '鵝',
  '鹂': '鸝',
  '鹏': '鵬',
  '麦': '麥',
  '黄': '黃',
  '黑': '黑',
  '默': '默',
  '鼓': '鼓',
  '龙': '龍',
  '龚': '龔',
  '龟': '龜'
};

// 预排序的繁简转换映射表
const ZH_TW_ENTRIES_SORTED = Object.entries(ZH_TW_MAP)
  .sort((a, b) => b[0].length - a[0].length);

// 简繁转换函数 - 按词组长度降序替换
export function convertChinese(text, mode) {
  if (mode !== 'to-tw' || !text) return text;

  let result = text;
  for (const [key, value] of ZH_TW_ENTRIES_SORTED) {
    const escapedKey = key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const regex = new RegExp(escapedKey, 'g');
    result = result.replace(regex, value);
  }
  return result;
}

// 应用自定义替换规则
export function applyReplaceRules(text, rules) {
  if (!rules || !rules.trim()) return text;

  const lines = rules.split('\n');
  let result = text;

  for (const line of lines) {
    if (!line.includes('=')) continue;
    const idx = line.indexOf('=');
    const pattern = line.substring(0, idx).trim();
    const replacement = line.substring(idx + 1).trim();
    if (!pattern) continue;

    try {
      const regex = new RegExp(pattern, 'g');
      result = result.replace(regex, replacement);
    } catch (e) {
      // 无效的正则表达式，跳过
    }
  }
  return result;
}
